sudo: required
services:
  - docker
before_install:
  - docker build -t phonekham/docker-react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true  phonekham/docker-react-test npm test
after_success:
  - docker build -t phonekham/docker-complex-client ./client
  - docker build -t phonekham/docker-complex-nginx ./nginx
  - docker build -t phonekham/docker-complex-server ./server
  - docker build -t phonekham/docker-complex-worker ./worker
  #   Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Take those images and push to dockerhub
  - docker push phonekham/docker-complex-client
  - docker push phonekham/docker-complex-nginx
  - docker push phonekham/docker-complex-server
  - docker push phonekham/docker-complex-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-ap-southeast-1-630165435469
  bucket_path: docker-complex
  on:
    branch_master: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
